.\" **** FIXALL ****
.TH man 8 "11 Jul 2012" "1.0" "fixall man page"
.SH NAME
fixall 1.0.0
.SH SYNOPSIS
fixall \- Fixes everything!
.SH DESCRIPTION
Fixes all of your problems -all of them- guaranteed!
.SH OPTIONS
Fixall does currently not take any options. However, you can supply your username.
.SH SEE ALSO
sl(7)
.SH BUGS
No known bugs.
.SH AUTHOR
Berik Visschers (berik@visschers.nu)
